[package]
name = "dedupetool"
version = "0.1.0"
authors = ["Octavia Togami <octavia.togami@gmail.com>"]
edition = "2018"

[dependencies]
console = "0.14"
libc = "0.2"
size_format = "1"
thiserror = "1"
structopt = "0.3"

[dependencies.num-format]
version = "0.4.0"
features = ["with-system-locale"]

[dependencies.tokio]
version = "1"
features = ["sync", "rt-multi-thread", "macros", "fs"]
