[package]
name = "dedupetool"
version = "0.1.0"
authors = ["Octavia Togami <octavia.togami@gmail.com>"]
license = "GPL-3.0-or-later"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
strip = true

[dependencies]
console = "0.15.0"
libc = "0.2.119"
num-format = "0.4.0"
size_format = "1.0.2"
thiserror = "1.0.30"

[dependencies.clap]
version = "3.1.6"
features = ["derive"]

[dependencies.tokio]
version = "1.17.0"
features = ["sync", "rt-multi-thread", "macros", "fs"]
